### ISSUE TITLE
[Feature request]: accept option to include custom css

### ISSUE THREAD

**Issue by zark0-UwU** [gofiber/swagger#2]
I would be neat to be able to set a custom css on top of the existing one, I personally hate the default color theme used by Shagger, and i think mos developers would prefer a dark them for my api's documentations, so i would like to see if that would be possible.

How?, adding a css string or file descriptor, they would be different fields to differenciate them

**Comment by arsmn** [comment]
You can use ```CustomStyle``` config now.
