### ISSUE TITLE
Reverse Proxy configuration

### ISSUE THREAD

**Issue by lucasoares** [gofiber/swagger#3]
Hello.

I use a reverse proxy (Istio+Envoy) and I'm unable to configure swagger using fiber correctly.

I'm configuring the swagger handler like this:
```
	app.Get("/docs/*", swagger.HandlerDefault)
```

But when I try to access it from the proxy, which is a URL like this:
```
https://proxy-host/some/custom/path/docs
```

The current implementation redirects me to:
```
https://proxy-host/docs/index.html
```

Instead of
```
https://proxy-host/some/custom/path/docs/index.html
```

The `Try it out` button also doesn't works because it is trying to send the request to the incorrect path. It should send the request to `https://my-proxy-host/custom/path/channels`.

Screenshot with this example:
![image](https://user-images.githubusercontent.com/10624972/169447054-023fe342-c5cc-46f2-8866-487fcfe11e6f.png)

Also, `TrustedProxies` and `EnableTrustedProxyCheck` options don't fix this issue. And even it could fix my reverse proxy doesn't have a fixed IP, which would be impossible to configure using the available options. I think you guys should look how Spring Boot manages this and maybe this is even a `fiber` issue (fixing the `c.Redirect` func) instead of a `gofiber swagger` issue: https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto.webserver.use-behind-a-proxy-server

Thanks.

**Comment by ReneWerner87** [comment]
@arsmn have you a clue? Can you take over ?
Have not much experience with the swagger middleware.

**Comment by arsmn** [comment]
Sure. I will check it ASAP.

**Comment by lucasoares** [comment]
I made it work changing how the redirect is made..

To the "Try it out" button to work I just set in my own application the `basePath` of the swag's `docs.SwaggerInfo.BasePath`

**Comment by lucasoares** [comment]
Also, what is the difference between this repository and [swaggo/fiber-swagger](https://github.com/swaggo/fiber-swagger)?

**Comment by lucasoares** [comment]
Also @ReneWerner87 @arsmn this is definately not a question-issue. It is a BUG or at lease a feature request.
