### ISSUE TITLE
Swag is not recognized as an internal or external command

### ISSUE THREAD

**Issue by rngallen** [gofiber/swagger#5]
My trying to run `swag init` but I got some command error

`'swag' is not recognized as an internal or external command,
operable program or batch file.`

![Untitled](https://user-images.githubusercontent.com/47332486/169742262-f8a0b40b-8362-4748-871b-048cc55b1691.png)

go version 1.18.2
Fiber version 2.33.0

**Comment by dassump** [comment]
You need to install swag with the command `go install github.com/swaggo/swag/cmd/swag@latest`.
If you've already done that, try running like this `$(go env GOPATH)/bin/swag`
