### ISSUE TITLE
Swagger does not compile on GoFiber v2.50.0

### ISSUE THREAD

**Issue by malusev998** [gofiber/swagger#67]
Since the breaking change of `GetReqHeaders` now returns `map[string][]string` instead of `map[string]string`
Code using swagger package no longer compiles.

Fails build here:

https://github.com/gofiber/swagger/blob/main/swagger.go#L81

**Comment by ReneWerner87** [comment]
thx for the report, we will fix this asap

**Comment by ReneWerner87** [comment]
fixed with release https://github.com/gofiber/swagger/releases/tag/v0.1.14
