### ISSUE TITLE
need to run `swag init` every time to update schema

### ISSUE THREAD

**Issue by KunalSin9h** [gofiber/swagger#73]
When i run my app using `go run main.go serve` (i am using cobra cli framework) then the swagger.json is not update with the updated code (comments). I have to run swag init everytime.

**Comment by Kerod-Fresenbet-Gebremedhin2660** [comment]
This is clearly outlined in the documentation. You could use any number of task runners to run the swagger generation before running the server.

**Comment by KunalSin9h** [comment]
thanks,

task runners? i am using `husky` for generating swagger specs before commiting. 
but i manually run `swag --init` before running the application.

**Comment by Kerod-Fresenbet-Gebremedhin2660** [comment]
@KunalSin9h you could use a makefile for instance and create an instruction to run swag init first before running go as so.

```
run:
	@swag init
	@go run main.go
```

**Comment by KunalSin9h** [comment]
thanks @Kerod-Fresenbet-Gebremedhin2660
