### ISSUE TITLE
Not compatible with v3 

### ISSUE THREAD

**Issue by ethanperrine** [gofiber/swagger#77]
When trying to implement in API code, this error appears:

[{
	"message": "cannot use GoSwagger.New(GoSwagger.Config{…}) (value of type func(*\"github.com/gofiber/fiber/v2\".Ctx) error) as func(\"github.com/gofiber/fiber/v3\".Ctx) error value in argument to app.Get",
}]

**Comment by Auxority** [comment]
Having the same issue here.

**Comment by gaby** [comment]
None of the external middlewares have been migrated to c3 yet. That will be done once we are closer to v3 release. :-)

https://github.com/gofiber/fiber?tab=readme-ov-file#%EF%B8%8F-attention
